---
- name: Gather Firmware Inventory
  hosts: r640
  gather_facts: false

  tasks:
  - name: Gather Installed Firmware Inventory
    dellemc.openmanage.idrac_firmware_info:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ username }}"
      idrac_password: "{{ password }}"
      validate_certs: false
    delegate_to: localhost
    register: firmware

  - name: Display Firmware
    debug:
      var: firmware 


