---
- name: Gather Firmware Inventory
  hosts: r640
  gather_facts: false

  tasks:
  - name: Gather Installed Firmware Inventory
    dellemc.openmanage.dellemc_get_firmware_inventory:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ username }}"
      idrac_password: "{{ password }}"
      validate_certs: false
    delegate_to: localhost
   


