---
- name: Gather iDrac System Inventory
  hosts: r640
  gather_facts: false

  tasks:
  - name: Gather idrac info
    dellemc.openmanage.idrac_system_info:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      validate_certs: false
    delegate_to: localhost
    register: info

  - name: Display info
    debug:
      var: info

