---
- name: Gather iDrac System Inventory
  hosts: r640
  gather_facts: false

  tasks:
  - name: Gather idrac info
    dellemc.openmanage.idrac_system_info:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      validate_certs: false
    delegate_to: localhost

  - name: Display iDrac Power State
    debug:
      msg: "{{ system_info.System.PowerState }}"
   
  - name: Display Model
    debug:
      msg: "{{ system_info.System.Model }}"

 
  - name: Display iDrac URL
    debug:
      msg: "{{ system_info.System.iDRACURL }}"


  - name: Display Memory
    debug:
      msg: "{{ system_info.Systm.SysMemTotalSize }}"
